//settings
export const TOGGLE_COLLAPSED_NAV = "TOGGLE_COLLAPSE_MENU";
export const UPDATE_WINDOW_WIDTH = "UPDATE_WINDOW_WIDTH ";
export const UPDATE_THEME_TYPE = "UPDATE_THEME_TYPE";
export const UPDATE_LAYOUT_TYPE = "UPDATE_LAYOUT_TYPE";
export const UPDATE_THEME_COLOR = "UPDATE_THEME_COLOR";
export const UPDATE_NAV_STYLE = "NAV_STYLE";

//people
export const FETCH_PEOPLE_STARTED = "FETCH_PEOPLE_STARTED";
export const FETCH_PEOPLE_SUCCESS = "FETCH_PEOPLE_SUCCESS";
